study_name: "U251_Environment_Comparison"
outdir: "./ANALYSIS/results_environment"

# --- INPUTS ---
input: "./ANALYSIS/metadata.csv"
contrasts: "./ANALYSIS/contrasts_env.csv"
matrix: "./ANALYSIS/results_human_final/star_salmon/salmon.merged.gene_counts.tsv"
transcript_length_matrix: "./ANALYSIS/results_human_final/star_salmon/salmon.merged.gene_lengths.tsv"

# Absolute paths
gtf: "/wsu/home/go/go24/go2432/u251-transcriptomic-evolution/ANALYSIS/refs/human/GRCh38.primary_assembly.annotation.gtf.gz"
gene_sets_files: "/wsu/home/go/go24/go2432/u251-transcriptomic-evolution/ANALYSIS/refs/pathways/combined_human.gmt"

# --- GSEA SETTINGS ---
gsea_run: true
gsea_permute: "gene_set"
gsea_metric: "Diff_of_Classes"
gsea_nperm: 1000
gsea_rnd_seed: "1234"
gsea_scoring_scheme: "weighted"
gsea_sort: "real"
gsea_order: "descending"
gsea_set_max: 500
gsea_set_min: 15
gsea_norm: "meandiv"
gsea_rnd_type: "no_balance"
gsea_make_sets: true
gsea_median: false
gsea_num: 100
gsea_plot_top_x: 20
gsea_save_rnd_lists: false
gsea_zip_report: false

# --- GPROFILER SETTINGS ---
gprofiler2_run: true
gprofiler2_organism: "hsapiens"

# --- DESEQ2 / FILTERING ---
exploratory_main_variable: "Environment"
exploratory_clustering_method: 'ward.D2'
deseq2_vs_method: 'vst'
deseq2_min_replicates_for_replace: 99
differential_subset_to_contrast_samples: false
